FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-noto-cjk \
    mecab \
    libmecab-dev \
    libgomp1 \
  && rm -rf /var/lib/apt/lists/*


WORKDIR /app

RUN python -m pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY data ./data

ENV PYTHONPATH=/app
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0
ENV STREAMLIT_SERVER_PORT=8501

EXPOSE 8501

CMD ["streamlit", "run", "app/ui/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
